name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Show .NET info
        run: dotnet --info

      - name: Clean
        run: dotnet clean AriaAPI.sln -c Release --disable-build-servers

      - name: Restore dependencies
        run: dotnet restore AriaAPI.sln --disable-build-servers

      - name: Build
        run: dotnet build AriaAPI.sln --no-restore -c Release --disable-build-servers -maxcpucount:1

      - name: Test
        run: dotnet test AriaAPI.Tests/AriaAPI.Tests.csproj --no-build --no-restore -c Release --verbosity normal
